language: python

python:
  - "2.7"
  - "3.7"
  - "3.6"

dist: xenial

install:
  - pip install -r requirements.pip
  - pip install -r requirements-dev.pip
  - pip install -e .

script: bash coverage.sh
